# Generated by Django 4.0.4 on 2023-04-08 12:52

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_account_status_alter_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[(core.models.UserAccountStatus['ACTIVE'], 'active'), (core.models.UserAccountStatus['DEACTIVATED'], 'deactivated'), (core.models.UserAccountStatus['SUSPENDED'], 'suspended')], default=core.models.UserAccountStatus['ACTIVE'], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(core.models.UserRole['ADMIN'], 'admin'), (core.models.UserRole['EDITOR'], 'editor'), (core.models.UserRole['VIEWER'], 'viewer')], default=core.models.UserRole['VIEWER'], max_length=20, null=True),
        ),
    ]
