# Generated by Django 4.0.4 on 2023-04-08 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_account_status_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_status',
        ),
    ]
