# Generated by Django 4.0.4 on 2023-04-10 17:51

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_user_role_user_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[(core.models.UserAccountStatus['ACTIVE'], 'active'), (core.models.UserAccountStatus['DEACTIVATED'], 'deactivated'), (core.models.UserAccountStatus['SUSPENDED'], 'suspended')], default=core.models.UserAccountStatus['ACTIVE'], max_length=20),
        ),
    ]
