# Generated by Django 4.0.4 on 2023-04-10 17:56

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated'), ('suspended', 'Suspended')], default=core.models.UserAccountStatus['ACTIVE'], max_length=20),
        ),
    ]
